# Generated by Django 2.2.11 on 2020-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_respuesta_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='titulo_binario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
