# Generated by Django 2.2.11 on 2020-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='gravedad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
