# Generated by Django 2.2.11 on 2020-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_gravedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
