# Generated by Django 2.2.11 on 2020-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_consulta_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dia',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
