# Generated by Django 2.2.11 on 2020-03-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('codigo', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Usado', 'Usado'), ('Cancelado', 'Cancelado')], max_length=30)),
            ],
        ),
    ]
