# Generated by Django 2.2.11 on 2020-03-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.Persona'),
        ),
    ]
