# Generated by Django 2.2.11 on 2020-03-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_consulta_ciudadano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre_y_apellidos',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=150),
        ),
    ]
