# Generated by Django 2.2.11 on 2020-03-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_auto_20200328_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='año_nacimiento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dia_nacimiento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mes_nacimiento',
            field=models.PositiveIntegerField(),
        ),
    ]
