# Generated by Django 2.2.11 on 2020-03-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0011_auto_20200328_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=100, null=True),
        ),
    ]
